const TECH = {
	NODE_JS: 'Node.js',
	TYPESCRIPT: 'Typescript',
	REACT: 'React',
	POSTGRESQL: 'PostgreSQL',
	NEST_JS: 'NestJS',
	NEXT_JS: 'Next.js',
	REDIS: 'Redis',
	STRIPE: 'Stripe',
	MUI: 'Material UI',
	JWT: 'JWT',
	EXPRESS: 'Express',
	REDUX: 'Redux',
	SOCKET_IO: 'Socket.io',
	HEROKU: 'Heroku',
	AWS: 'AWS',
	NETLIFY: 'Netlify',
	DOCKER: 'Docker',
	SWAGGER: 'Swagger',
	POSTMAN: 'Postman',
	MOCHA: 'Mocha',
	CHAI: 'Chai',
	JEST: 'Jest',
	SEQUELIZE: 'Sequelize',
	PRISMA: 'Prisma',
	PASSPORT: 'Passport',
	BOOTSTRAP: 'Bootstrap',
	JASMINE: 'Jasmine',
	NPM: 'NPM',
	YARN: 'Yarn',
	GITHUB: 'Github',
	WEB: 'Web'
};

export default TECH;
