FROM node:17.2.0-alpine3.12
RUN apk add --no-cache bash curl

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --silent

COPY . .

RUN yarn build

CMD ["yarn", "start:prod"]